services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "5003:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data
    networks:
      - metabase-network

volumes:
  metabase-data:

networks:
  metabase-network:
    driver: bridge