# Generated by Django 4.2.19 on 2025-03-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form_id',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
