# Generated by Django 5.1.7 on 2025-03-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_formsubmission_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformfield',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='userformfield',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='userformfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userformfield',
            name='position',
        ),
    ]
