# Generated by Django 5.1.7 on 2025-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patientdemographics_formsubmission_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdemographics',
            name='referral_number',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
