# Generated by Django 5.1.7 on 2025-03-19 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_patientdemographics_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdemographics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientdemographics',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='patientdemographics',
            name='referral_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
