# Generated by Django 5.1.7 on 2025-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_patientdemographics_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='submitted_at',
            field=models.DateTimeField(),
        ),
    ]
