# Generated by Django 5.1.7 on 2025-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_formsubmission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
