# Generated by Django 5.1.7 on 2025-03-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_formsubmission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
